version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_PASSWORD_SEEDER=true
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_USER=cassandra_admin
      - CASSANDRA_PASSWORD=supersecure
    volumes:
      - vol_cassandra_data:/var/lib/cassandra
    networks:
      - app_shared_network

  mongo:
    image: mongo:8.0.0-rc4-jammy
    ports:
      - "27017:27017"
    volumes:
      - vol_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: felipe
      MONGO_INITDB_ROOT_PASSWORD: 2135654felipedsaf54654aAndressdf545
    networks:
      - app_shared_network

  db:
    image: postgres:13.15-bullseye
    ports:
      - "5432:5432"
    volumes:
      - vol_postgres_data:/data/postgres
    environment:
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: 2135654felipedsaf54654aAndressdf545
      POSTGRES_DB: jave_database
    networks:
      - app_shared_network

  frontend:
    image: tu_usuario/frontend:latest  # Asegúrate de construir y subir esta imagen
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_shared_network

  backend:
    image: tu_usuario/backend:latest  # Asegúrate de construir y subir esta imagen
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - db
      - cassandra
    command: sh -c "sleep 180 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app_shared_network

volumes:
  vol_mongo_data:
  vol_postgres_data:
  vol_cassandra_data:

networks:
  app_shared_network:
