version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
