name: Docker Build Cloud CI

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build backend using Docker Build Cloud
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: japipe05/jave-backend:latest
          builder: cloud-japipe05-javerianacloud
          provenance: true

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build frontend using Docker Build Cloud
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: japipe05/jave-frontend:latest
          builder: cloud-japipe05-javerianacloud
          provenance: true
