name: buiild and publish image ro Docker hub

on:
  [workflow_dispatch]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: build image
      run: |
        docker build . --file backend/Dockerfile -t japipe05/backend:latest
        docker build . --file frontend/Dockerfile -t japipe05/frontend:latest
    - name: push image to docker hub
      run: |
        docker login -u japipe05 -p "${{ secrets.DOCKER_PAT }}"
        docker push japipe05/backend:latest
        docker push japipe05/frontend:latest
    
